### ISSUE TITLE
Update latitude and longitude field names on filtered HWMs CSV endpoint

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/STNServices2#112]
To make this endpoint readily compatible with AGOL, change the `latitude_dd` and `longitude_dd` field names to simply `latitude` and `longitude`. The filtered instruments endpoint already returns lat/long fields named that way, so this would also be an improvement in consistency. 

endpoint in question: `https://stn.wim.usgs.gov/STNServices/HWMs/FilteredHWMs.csv?Event=180&EventType=&EventStatus=0&States=&County=&HWMType=&HWMQuality=&HWMEnvironment=&SurveyComplete=&StillWater=`

**Comment by BlakeDraper** [comment]
Also would be best if the `latitude' and `longitude` fields are the first in order of the table (again for AGOL compatibility, not just arbitrarily)

**Comment by troddick** [comment]
Done and live.
