### ISSUE TITLE
XML not working for Sensor Types endpoint

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/STNServices2#133]
> In this case, the JSON works at   https://stn.wim.usgs.gov/STNServices/SensorTypes.json
> But the xml does not:   https://stn.wim.usgs.gov/STNServices/SensorTypes.xml

**Comment by HansVraga** [comment]
Some progress here, but Todd tested and though he got a CSV, it had sensors from more than one event returned in it. He tried https://stn.wim.usgs.gov/fev/#HarveyAug2017 and described his workflow below.

>I see lots of stuff now working that wasn't previously working (mainly some sensor counts I was doing via Google Sheets that are now hitting the web services and returning the correct counts).  However, I did try one of Lauren's suggested links just now -- the one for Harvey.  Then I went to GET DATA, clicked the Sensor Data, and downloaded the CSV version.  What I got was a CSV with sensors for many (all?) events instead of just for Harvey.

**Comment by HansVraga** [comment]
I tested it too and got a similar result - if you view the .json, you see only 27 entries where event_id = 180 (Harvey)

https://stn.wim.usgs.gov/STNServices/Instruments.json?Event=180&States=&County=&SensorType=&CurrentStatus=&CollectionCondition=&DeploymentType=

**Comment by HansVraga** [comment]
Upon further investigation, this is a FEV issue https://github.com/USGS-WiM/FEV/issues/187

**Comment by HansVraga** [comment]
I've mucked up this issue - all of this should have been tracked here: https://github.com/USGS-WiM/STNServices2/issues/135
