### ISSUE TITLE
Create new EC2 for new test environment

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/STNServices2#144]
We need a new EC2 instance to use as a testing environment during the upcoming hurricane season.

**Comment by DanielJBeckman** [comment]
Are we cloning an EC2 or is this a scratch build?

**Comment by HansVraga** [comment]
From scratch. Same size as current test.

**Comment by aaronstephenson** [comment]
This will be a plain vanilla web server, right? Running Windows? Which version (2012R2, 2016, 2019)?

**Comment by lprivette** [comment]
Sorry, should have included this in the original ticket.

Windows, 2012R2 (Same as current prod on Toad)

**Comment by aaronstephenson** [comment]
FQDN: stntest.wim.usgs.gov
(this has been reassigned from the now-discarded test server)

Public IP address: 3.95.53.54
Private IP address: 10.240.10.213 (use this when RDP'ing from the WMA Bastion server)

Web traffic (80, 443) is open to the whole internet, but RDP traffic (3389) is restricted to the WMA Bastion Server: 18.208.5.35, which itself is restricted to USGS HQ, UMid WI office, and a handful of single computers.

Local OS user credentials can be created by a local OS Administrator, just ask.
