### ISSUE TITLE
Clone "stn" prod RDS

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/STNServices2#146]
We'll be using the clone as a test db within our new testing environment. relates to https://github.com/USGS-WiM/STNServices2/issues/144

**Comment by aaronstephenson** [comment]
@DanielJBeckman you want to work on this one together?

**Comment by aaronstephenson** [comment]
stntest.ct8t2yrz6ztl.us-east-1.rds.amazonaws.com

Same credentials as prod STN DB
