### ISSUE TITLE
Need administrator access to STNWebTest ec2 instance on WMA account

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/STNServices2#149]

**Comment by aaronstephenson** [comment]
Just forgot to join the server to the domain and add the WIM user group to the Administrators group. Just a moment...

**Comment by aaronstephenson** [comment]
Lots of system updates, going to take longer than expected.

**Comment by aaronstephenson** [comment]
I misspoke, the old server was never part of the domain, there were just local user accounts. So I created one for you and added you to the Administrators group. You should be good now.
