### ISSUE TITLE
Add STNWebTest to nightly shutdown script

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/STNServices2#150]
STNWebTest used to shut down nightly when it was on the WIM account, but now that it's in the WMA subaccount I noticed that it's no longer shutting down.

I don't know how the shutdown scripts work or if they could work across subaccounts, but if it's possible add it to the list?

**Comment by DanielJBeckman** [comment]
This is done.

**Comment by lprivette** [comment]
Reopening because I logged on today and the server was still running from last week.

**Comment by aaronstephenson** [comment]
Looks like the lambda function is failing because there is an old instance ID in the text file that no longer exists. I removed that ID from the file, so this should be working again.
