### ISSUE TITLE
Render a new Test database for STNServices from the current Prod database

### ISSUE THREAD

**Issue by DanielJBeckman** [USGS-WiM/STNServices2#153]
Aaron,

This definitely needs your oversight. We recently built out a container based STNservices backend but we believe that the current STNservices test dataset is stale and causing bugs in our testing of the new service. **Can we produce a cloned dataset of the current STN Prod database** to use to certify the new service?  

Concerns: Storm Season is under way and the STN Prod database is taking data. How can we clone it safely?

**Comment by HansVraga** [comment]
Chiming in here - I think we can use the RDS backups in S3 to build a new test STN RDS? A recent backup would suffice - we don't need Prod as it currently is.

**Comment by aaronstephenson** [comment]
Yes, we can repopulate test from prod using a backup. We have hourly backups available due to Laura. Which should probably be turned off now @lprivette ?

**Comment by aaronstephenson** [comment]
@PatrickMooreUSGS are you available to assist this week?

**Comment by lprivette** [comment]
@aaronstephenson last I checked they were still logging data. I'll checkin with athena and make an issue for it if it's time to turn it off.

**Comment by aaronstephenson** [comment]
Oh in that case no worries. I thought, with the storm past... ¯\_(ツ)_/¯ but what do I know about field ops.

**Comment by DanielJBeckman** [comment]
Sounds like we have a plan then.

**Comment by aaronstephenson** [comment]
Restore complete. STNTest now has all the data from STN prod as of an hour or so ago.

**Comment by lprivette** [comment]
did we build a new test RDS or overwrite current test?

**Comment by aaronstephenson** [comment]
It's new, but has all the same connection info. It should "just work".

**Comment by lprivette** [comment]
ok whew was just worried for a sec that we have overwritten the existing test DB. SAWSC is doing a training today, but all good. Thanks Aaron!

**Comment by lprivette** [comment]
@aaronstephenson how does it work if it has all the same connection info? sorry, I'm not understanding how they're different but the same.
