### ISSUE TITLE
delete ObjectivePoint endpoint update

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/STNServices2#25]
Look for any op_measurements that this OP is on and remove them. 
Note: if the instrument_status has only this one op tapedown, the 4 fields related should be cleared as well. (sensor_elevation, ws_elevation, gs_elevation, vdatum_id), but if there are more than one tapedown, and we remove just his related OP one, the instrument_status fields can remain populated, since they may be from one of the other tapedowns.

**Comment by HansVraga** [comment]
DONE!
