### ISSUE TITLE
Broken endpoint needs investigating

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/STNServices2#41]
Dont know what is going on, but this is failing and needs investigation:

http://stntest.wim.usgs.gov/STNServices/Instruments.json?Event=&EventType=2&EventStatus=0&States=&County=&CurrentStatus=&CollectionCondition=&DeploymentType=

Affects STNDataPortal, maybe others

**Comment by HansVraga** [comment]
During cleanup, tried:
http://stntest.wim.usgs.gov/STNServices2/Instruments.json?Event=&EventType=2&EventStatus=0&States=&County=&CurrentStatus=&CollectionCondition=&DeploymentType=

and it worked. (note slight URL change to reference STNServices2) Assumed fixed in the past...
