### ISSUE TITLE
Data file metadata link to file broken

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNServices2#61]
Many Data files ~are either misclassified or the~ link to their metadata is broken. ~Fixing this requires manual review of each broken link.~

**Comment by HansVraga** [comment]
@troddick to look into writing a script to parse through all the file links to hit S3 and see if the file is still there, and generate a list of files that aren't there (if there are any).

**Comment by troddick** [comment]
1372 missing files from s3.

https://docs.google.com/spreadsheets/d/1aXHp93bZRiTDhvsDq7TGucKwvcTtyvMU0zfGtisphtg/edit#gid=199945349

**Comment by troddick** [comment]
Missing files from 2016 Louisiana Flood (this may be all of them):
https://drive.google.com/drive/folders/0BygT1gkOzi3SZXlpbGxUWjBRVEE

**Comment by HansVraga** [comment]
Tried to engage WMA on numerous occasions to clean this up, no answer. Closing.
