### ISSUE TITLE
Add a last-updated date, implement concurrent edits rejection

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/STNServices2#99]
Add a last-updated date/time to every object, write it with every update to that object, and check it before every edit to ensure that there hasn't been a change to the underlying item in between when a user loaded it and when they made the change.

Either that, or we build in a true audit table to this system.

**Comment by troddick** [comment]
every put/post, check last_edit date. see if changed since they grabbed it. Either database feature or add new field to every table for last_edit

**Comment by troddick** [comment]
Looking into: 
https://wiki.postgresql.org/wiki/Audit_trigger_91plus

**Comment by troddick** [comment]
add last_updated and last_updated_by fields to all objects of importance for edit tracking

**Comment by troddick** [comment]
Will add 'last_updated' and 'last_updated_by' to the following tables:
approval
contact
data_file
events
files
hwm
instrument
instrument_status
landownercontact
members
network_name_site
network_type_site
objective_point
op_control_identifier
op_measurements
peak_summary
reporting_metrics
reportmetric_contact
site_housing
sites
sources

**Comment by troddick** [comment]
Once complete, integrate into services to handle updating these fields on every post and put.

**Comment by troddick** [comment]
both fields added to tables in stntest db

**Comment by troddick** [comment]
all post/put endpoints updated to update these 2 fields in stntest services
